export const PROFILES = {
  calm: {
    name: 'דורון',
    relation: 'אח',
    age: 34,
    avatar: '#6f8a6c',
    status: 'יציב',
    statusKind: 'calm',
    statusBlurb: 'שינה תקינה, נטילת תרופות עקבית',
    days: [
      { d: 'א׳', sleep: 7.5, mood: 3, meds: true },
      { d: 'ב׳', sleep: 8, mood: 3, meds: true },
      { d: 'ג׳', sleep: 7, mood: 4, meds: true },
      { d: 'ד׳', sleep: 7.5, mood: 3, meds: true },
      { d: 'ה׳', sleep: 8, mood: 3, meds: true },
      { d: 'ו׳', sleep: 7.5, mood: 4, meds: true },
      { d: 'ש׳', sleep: 7, mood: 3, meds: true },
    ],
    behaviors: [],
    todayMeds: { taken: 2, total: 2, by: 'יעל' },
    lastVisit: { by: 'אבא', when: 'אתמול 19:30' },
  },
  warning: {
    name: 'דורון',
    relation: 'אח',
    age: 34,
    avatar: '#c69230',
    status: 'סימני אזהרה מוקדמים',
    statusKind: 'warn',
    statusBlurb: 'שינה ירדה ל־4.5 שעות שני לילות ברצף',
    days: [
      { d: 'א׳', sleep: 7, mood: 3, meds: true },
      { d: 'ב׳', sleep: 7.5, mood: 3, meds: true },
      { d: 'ג׳', sleep: 6.5, mood: 4, meds: true },
      { d: 'ד׳', sleep: 6, mood: 4, meds: true },
      { d: 'ה׳', sleep: 5, mood: 5, meds: true },
      { d: 'ו׳', sleep: 4.5, mood: 5, meds: true },
      { d: 'ש׳', sleep: 4.5, mood: 6, meds: false },
    ],
    behaviors: [
      { when: 'אתמול 23:40', text: 'דיבור מהיר ולא קשור, התקשר 3 פעמים' },
      { when: 'היום 07:15', text: 'יזמות מוגזמת — תכנון נסיעה פתאומית' },
    ],
    todayMeds: { taken: 0, total: 2, by: null },
    lastVisit: { by: 'אמא', when: 'היום 09:10' },
  },
  crisis: {
    name: 'דורון',
    relation: 'אח',
    age: 34,
    avatar: '#b03a2e',
    status: 'מצב משברי',
    statusKind: 'crisis',
    statusBlurb: '48 שעות ללא שינה · התנהגות תוקפנית מדווחת',
    days: [
      { d: 'א׳', sleep: 6, mood: 4, meds: true },
      { d: 'ב׳', sleep: 5.5, mood: 4, meds: true },
      { d: 'ג׳', sleep: 5, mood: 5, meds: true },
      { d: 'ד׳', sleep: 4, mood: 5, meds: false },
      { d: 'ה׳', sleep: 3, mood: 6, meds: false },
      { d: 'ו׳', sleep: 1.5, mood: 7, meds: false },
      { d: 'ש׳', sleep: 0, mood: 8, meds: false },
    ],
    behaviors: [
      { when: 'אתמול 02:10', text: 'עזב את הבית, חזר ב־04:30' },
      { when: 'אתמול 14:00', text: 'הוצאות גדולות — קניות פזרניות' },
      { when: 'היום 06:20', text: 'אגרסיביות מילולית, איומים' },
      { when: 'היום 08:45', text: 'דיבור מהיר, אמונות גרנדיוזיות' },
    ],
    todayMeds: { taken: 0, total: 2, by: null },
    lastVisit: { by: 'אמא', when: 'בוקר, 06:00' },
  },
};
